Content4 pull-request
FrontProjectTeam/GameNest pull request #5
Opened 2024-10-26 06:38 UTC by kyoungjooo

### 설명 Desctiption
- 화면에 랜덤으로 나타나는 문장을 입력하는 타자게임입니다.
- 구현 기능
1. 화면에 배열안에 있는 객체의 콘텐츠가 화면에 랜덤으로 그려집니다.
2. 텍스트 입력란에 입력후 엔터 혹은 완료 버튼을 누르면 입력한 문장과 화면의 문장이 일치하는지 확인합니다.
3. 입력한 문장이 화면과 같으면 점수가 +10점 추가됩니다.
4. 입력한 문장이 틀렸으면 점수가 -10점 차감되고(0점에서 틀리면 그대로 0점), 틀린문장수가 1개 더해집니다.
5. 정답률은 사용자가 풀은 총 문제수를 기준으로 산출됩니다.
6. 경과시간이 5분(300)초가 되면 게임이 종료됩니다.
7. 게임이 종료되면 최종 점수, 틀린 문장 수, 정답률을 모달창에 띄워줍니다.

### 테스트 방법 How to Test
1. 텍스트 입력란에 화면에 나타난 문장을 입력합니다.
2. 최종 결과와 내가 풀은 문제 수가 일치하는지 확인합니다.
3. 모달창에 뜬 결과와 최종 결과가 일치하는지 확인합니다.

### 기타 Ect
- 아직 미흡한 부분이 많은 것 같아요! 
1. 랜덤이 이전과 같은 문장이 나옴..
2. 게임 시작 버튼 없음
3. 게임 종료 후 타이머 동작 안 함
4. 더 필요한 기능이 있으면 알려주세요.
- 중복되는 코드가 많은 것 같은데 어떻게 정리할 수 있을까요..
- 함수안에 함수를 쓰지 않고 만들 수 있는 방법 ?

2024-11-01 09:48 UTC, parkjungyuxx requested changes
input 위에 위치한 텍스트의 텍스트 컬러가 가시성면에서 안좋은거같아요 밝은색으로 변경하면 좋을거같습니다!😀

2024-11-02 05:34 UTC, Beaconyx2025 approved these changes

2024-11-02 05:35 UTC, gimghoon approved these changes

2024-11-02 06:11 UTC, parkjungyuxx approved these changes
👍🏿

2024-11-02 06:12 UTC, merged